CREATE OR REPLACE TABLE RAW.WORLD_BANK_GDP (
    COUNTRY_CODE        VARCHAR(10),
    COUNTRY_NAME        VARCHAR(100),
    INDICATOR_CODE      VARCHAR(50),
    INDICATOR_NAME      VARCHAR(200),
    YEAR                INTEGER,
    VALUE               FLOAT,
    LOADED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.WORLD_BANK_INFLATION (
    COUNTRY_CODE        VARCHAR(10),
    COUNTRY_NAME        VARCHAR(100),
    INDICATOR_CODE      VARCHAR(50),
    INDICATOR_NAME      VARCHAR(200),
    YEAR                INTEGER,
    VALUE               FLOAT,
    LOADED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.WORLD_BANK_FX_RATES (
    COUNTRY_CODE        VARCHAR(10),
    COUNTRY_NAME        VARCHAR(100),
    INDICATOR_CODE      VARCHAR(50),
    INDICATOR_NAME      VARCHAR(200),
    YEAR                INTEGER,
    VALUE               FLOAT,
    LOADED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.WORLD_BANK_GOVT_DEBT (
    COUNTRY_CODE        VARCHAR(10),
    COUNTRY_NAME        VARCHAR(100),
    INDICATOR_CODE      VARCHAR(50),
    INDICATOR_NAME      VARCHAR(200),
    YEAR                INTEGER,
    VALUE               FLOAT,
    LOADED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

select * from raw.world_bank_gdp limit 10;

truncate table WORLD_BANK_GDP;
truncate table WORLD_BANK_INFLATION;
truncate table WORLD_BANK_FX_RATES;
truncate table WORLD_BANK_GOVT_DEBT;
truncate table pipeline_log;

