

-- ── 1. GDP growth year-over-year by country ──────────────────
CREATE OR REPLACE VIEW REPORTING.VW_GDP_GROWTH AS
SELECT
    COUNTRY_CODE,
    COUNTRY_NAME,
    YEAR,
    VALUE                                       AS GDP_USD,
    LAG(VALUE) OVER (
        PARTITION BY COUNTRY_CODE ORDER BY YEAR
    )                                           AS PREV_YEAR_GDP_USD,
    ROUND(
        (VALUE - LAG(VALUE) OVER (PARTITION BY COUNTRY_CODE ORDER BY YEAR))
        / NULLIF(LAG(VALUE) OVER (PARTITION BY COUNTRY_CODE ORDER BY YEAR), 0)
        * 100, 2
    )                                           AS GDP_GROWTH_PCT
FROM STAGING.MACRO_INDICATORS
WHERE METRIC_TYPE = 'GDP_USD'
ORDER BY COUNTRY_CODE, YEAR;

-- ── 2. Inflation vs GDP side by side (pivot-style) ──────────
CREATE OR REPLACE VIEW REPORTING.VW_MACRO_SUMMARY AS
SELECT
    g.COUNTRY_CODE,
    g.COUNTRY_NAME,
    g.YEAR,
    g.VALUE                                     AS GDP_USD,
    i.VALUE                                     AS INFLATION_PCT,
    f.VALUE                                     AS FX_RATE_TO_USD,
    d.VALUE                                     AS GOVT_DEBT_PCT_GDP
FROM
    (SELECT * FROM STAGING.MACRO_INDICATORS WHERE METRIC_TYPE = 'GDP_USD')       g
LEFT JOIN
    (SELECT * FROM STAGING.MACRO_INDICATORS WHERE METRIC_TYPE = 'INFLATION_PCT') i
    ON g.COUNTRY_CODE = i.COUNTRY_CODE AND g.YEAR = i.YEAR
LEFT JOIN
    (SELECT * FROM STAGING.MACRO_INDICATORS WHERE METRIC_TYPE = 'FX_RATE_TO_USD') f
    ON g.COUNTRY_CODE = f.COUNTRY_CODE AND g.YEAR = f.YEAR
LEFT JOIN
    (SELECT * FROM STAGING.MACRO_INDICATORS WHERE METRIC_TYPE = 'GOVT_DEBT_PCT_GDP') d
    ON g.COUNTRY_CODE = d.COUNTRY_CODE AND g.YEAR = d.YEAR
ORDER BY g.COUNTRY_CODE, g.YEAR;

-- ── 3. Materialized view — latest year snapshot per country ──
CREATE OR REPLACE MATERIALIZED VIEW REPORTING.MV_LATEST_MACRO AS
SELECT
    COUNTRY_CODE,
    COUNTRY_NAME,
    MAX(YEAR)                                   AS LATEST_YEAR,
    MAX(CASE WHEN METRIC_TYPE = 'GDP_USD'            THEN VALUE END) AS GDP_USD,
    MAX(CASE WHEN METRIC_TYPE = 'INFLATION_PCT'      THEN VALUE END) AS INFLATION_PCT,
    MAX(CASE WHEN METRIC_TYPE = 'FX_RATE_TO_USD'     THEN VALUE END) AS FX_RATE_TO_USD,
    MAX(CASE WHEN METRIC_TYPE = 'GOVT_DEBT_PCT_GDP'  THEN VALUE END) AS GOVT_DEBT_PCT_GDP
FROM STAGING.MACRO_INDICATORS
GROUP BY COUNTRY_CODE, COUNTRY_NAME;

-- Test your views
SELECT * FROM REPORTING.VW_GDP_GROWTH WHERE COUNTRY_CODE = 'USA' LIMIT 10;
SELECT * FROM REPORTING.VW_MACRO_SUMMARY WHERE YEAR = 2022 ORDER BY GDP_USD DESC;
SELECT * FROM REPORTING.MV_LATEST_MACRO ORDER BY GDP_USD DESC;


SHOW MATERIALIZED VIEWS IN SCHEMA FINANCE_PROJECT.REPORTING;

