-- Unified clean table combining all indicators
CREATE OR REPLACE TABLE STAGING.MACRO_INDICATORS AS
SELECT
    COUNTRY_CODE,
    COUNTRY_NAME,
    INDICATOR_CODE,
    INDICATOR_NAME,
    YEAR,
    ROUND(VALUE, 4)                             AS VALUE,
    CASE
        WHEN INDICATOR_CODE = 'NY.GDP.MKTP.CD'      THEN 'GDP_USD'
        WHEN INDICATOR_CODE = 'FP.CPI.TOTL.ZG'      THEN 'INFLATION_PCT'
        WHEN INDICATOR_CODE = 'PA.NUS.FCRF'          THEN 'FX_RATE_TO_USD'
        WHEN INDICATOR_CODE = 'GC.DOD.TOTL.GD.ZS'   THEN 'GOVT_DEBT_PCT_GDP'
        ELSE 'UNKNOWN'
    END                                         AS METRIC_TYPE,
    LOADED_AT
FROM RAW.WORLD_BANK_GDP

UNION ALL SELECT COUNTRY_CODE, COUNTRY_NAME, INDICATOR_CODE, INDICATOR_NAME,
    YEAR, ROUND(VALUE, 4), 'INFLATION_PCT', LOADED_AT FROM RAW.WORLD_BANK_INFLATION

UNION ALL SELECT COUNTRY_CODE, COUNTRY_NAME, INDICATOR_CODE, INDICATOR_NAME,
    YEAR, ROUND(VALUE, 4), 'FX_RATE_TO_USD', LOADED_AT FROM RAW.WORLD_BANK_FX_RATES

UNION ALL SELECT COUNTRY_CODE, COUNTRY_NAME, INDICATOR_CODE, INDICATOR_NAME,
    YEAR, ROUND(VALUE, 4), 'GOVT_DEBT_PCT_GDP', LOADED_AT FROM RAW.WORLD_BANK_GOVT_DEBT

WHERE VALUE IS NOT NULL
  AND YEAR BETWEEN 2000 AND 2023;

-- Verify
SELECT METRIC_TYPE, COUNT(*) AS ROW_COUNT FROM STAGING.MACRO_INDICATORS
GROUP BY METRIC_TYPE ORDER BY METRIC_TYPE;




CREATE OR REPLACE PROCEDURE STAGING.SP_REFRESH_MACRO_INDICATORS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- Build into a temp table first so MACRO_INDICATORS is never absent
    CREATE OR REPLACE TRANSIENT TABLE FINANCE_PROJECT.STAGING.MACRO_INDICATORS_NEW AS
    SELECT COUNTRY_CODE, COUNTRY_NAME, INDICATOR_CODE, INDICATOR_NAME,
           YEAR, ROUND(VALUE, 4) AS VALUE, 'GDP_USD' AS METRIC_TYPE, LOADED_AT
    FROM FINANCE_PROJECT.RAW.WORLD_BANK_GDP WHERE VALUE IS NOT NULL

    UNION ALL
    SELECT COUNTRY_CODE, COUNTRY_NAME, INDICATOR_CODE, INDICATOR_NAME,
           YEAR, ROUND(VALUE, 4), 'INFLATION_PCT', LOADED_AT
    FROM FINANCE_PROJECT.RAW.WORLD_BANK_INFLATION WHERE VALUE IS NOT NULL

    UNION ALL
    SELECT COUNTRY_CODE, COUNTRY_NAME, INDICATOR_CODE, INDICATOR_NAME,
           YEAR, ROUND(VALUE, 4), 'FX_RATE_TO_USD', LOADED_AT
    FROM FINANCE_PROJECT.RAW.WORLD_BANK_FX_RATES WHERE VALUE IS NOT NULL

    UNION ALL
    SELECT COUNTRY_CODE, COUNTRY_NAME, INDICATOR_CODE, INDICATOR_NAME,
           YEAR, ROUND(VALUE, 4), 'GOVT_DEBT_PCT_GDP', LOADED_AT
    FROM FINANCE_PROJECT.RAW.WORLD_BANK_GOVT_DEBT WHERE VALUE IS NOT NULL;

    -- Swap new into place atomically — no window where table is missing
    TRUNCATE TABLE FINANCE_PROJECT.STAGING.MACRO_INDICATORS;
    INSERT INTO FINANCE_PROJECT.STAGING.MACRO_INDICATORS 
    SELECT * FROM MACRO_INDICATORS_NEW;

    -- Clean up
    DROP TABLE IF EXISTS FINANCE_PROJECT.STAGING.MACRO_INDICATORS_NEW;

    RETURN 'Staging refresh complete: ' || CURRENT_TIMESTAMP();
END;
$$;


-- Task to refresh macro indicators
CREATE OR REPLACE TASK FINANCE_PROJECT.STAGING.TASK_REFRESH_STAGING
    WAREHOUSE = COMPUTE_WH
    SCHEDULE  = 'USING CRON 00 14 * * * America/New_York'   
AS
    CALL STAGING.SP_REFRESH_MACRO_INDICATORS();

GRANT EXECUTE TASK ON ACCOUNT TO ROLE SYSADMIN;

-- Activate the task (tasks are suspended by default)
ALTER TASK FINANCE_PROJECT.STAGING.TASK_REFRESH_STAGING RESUME;

-- Check task status
SHOW TASKS IN SCHEMA FINANCE_PROJECT.STAGING;

-- Check task run history
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD('DAY', -1, CURRENT_TIMESTAMP()),
    TASK_NAME => 'TASK_REFRESH_STAGING'
));


-- Check for missing data by country and metric
CREATE OR REPLACE VIEW REPORTING.VW_DATA_QUALITY AS
SELECT
    COUNTRY_CODE,
    COUNTRY_NAME,
    METRIC_TYPE,
    COUNT(*)                                    AS TOTAL_YEARS,
    MIN(YEAR)                                   AS EARLIEST_YEAR,
    MAX(YEAR)                                   AS LATEST_YEAR,
    ROUND(AVG(VALUE), 2)                        AS AVG_VALUE,
    ROUND(MIN(VALUE), 2)                        AS MIN_VALUE,
    ROUND(MAX(VALUE), 2)                        AS MAX_VALUE
FROM STAGING.MACRO_INDICATORS
GROUP BY COUNTRY_CODE, COUNTRY_NAME, METRIC_TYPE
ORDER BY COUNTRY_CODE, METRIC_TYPE;

-- Pipeline run log table
CREATE OR REPLACE TABLE RAW.PIPELINE_LOG (
    RUN_ID          INTEGER AUTOINCREMENT,
    RUN_TIMESTAMP   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    INDICATOR       VARCHAR(50),
    ROWS_LOADED     INTEGER,
    STATUS          VARCHAR(20),   -- 'SUCCESS' or 'FAILED'
    MESSAGE         VARCHAR(500)
);

-- Query to see latest pipeline runs
SELECT * FROM RAW.PIPELINE_LOG ORDER BY RUN_TIMESTAMP DESC LIMIT 20;

-- ── TASK 2: Runs AFTER Task 1 completes ─────────────────────

CREATE OR REPLACE TASK FINANCE_PROJECT.STAGING.TASK_REFRESH_REPORTING
    WAREHOUSE = COMPUTE_WH
    AFTER FINANCE_PROJECT.STAGING.TASK_REFRESH_STAGING  
AS
    -- Materialized Views refresh themselves; we just use this task to log the event
    INSERT INTO FINANCE_PROJECT.RAW.PIPELINE_LOG
        (INDICATOR, ROWS_LOADED, STATUS, MESSAGE)
    VALUES
        ('REPORTING_LAYER', 0, 'SUCCESS', 'Staging update complete. MV auto-refreshing.');


-- ── TASK 3: Runs AFTER Task 2 — final validation ────────────
CREATE OR REPLACE TASK FINANCE_PROJECT.STAGING.TASK_VALIDATE_PIPELINE
    WAREHOUSE = COMPUTE_WH
    AFTER FINANCE_PROJECT.STAGING.TASK_REFRESH_REPORTING
AS
BEGIN
    -- Check row counts look healthy, flag if something dropped
    INSERT INTO FINANCE_PROJECT.RAW.PIPELINE_LOG
        (INDICATOR, ROWS_LOADED, STATUS, MESSAGE)
    SELECT
        'VALIDATION',
        COUNT(*),
        CASE WHEN COUNT(*) > 100 THEN 'SUCCESS' ELSE 'WARNING — low row count' END,
        'Validation complete: ' || CURRENT_TIMESTAMP()
    FROM FINANCE_PROJECT.STAGING.MACRO_INDICATORS;
END;


-- ── Activate all tasks ( activate children first)
ALTER TASK FINANCE_PROJECT.STAGING.TASK_VALIDATE_PIPELINE RESUME;
ALTER TASK FINANCE_PROJECT.STAGING.TASK_REFRESH_REPORTING RESUME;
ALTER TASK FINANCE_PROJECT.STAGING.TASK_REFRESH_STAGING RESUME;


SELECT * FROM FINANCE_PROJECT.RAW.PIPELINE_LOG
ORDER BY RUN_TIMESTAMP DESC
LIMIT 10;

CALL FINANCE_PROJECT.STAGING.SP_REFRESH_MACRO_INDICATORS();

SELECT COUNT(*) FROM FINANCE_PROJECT.STAGING.MACRO_INDICATORS;

GRANT SELECT ON TABLE FINANCE_PROJECT.STAGING.MACRO_INDICATORS
TO ROLE SYSADMIN;


truncate table macro_indicators;

CREATE OR REPLACE MATERIALIZED VIEW FINANCE_PROJECT.REPORTING.MV_LATEST_MACRO AS
SELECT * 
FROM FINANCE_PROJECT.STAGING.MACRO_INDICATORS;


truncate MACRO_INDICATORS;

ALTER TABLE FINANCE_PROJECT.RAW.PIPELINE_LOG 
MODIFY COLUMN STATUS VARCHAR(50);